spring:
    kafka:
        bootstrap-servers: localhost:29092
        consumer:
            auto-offset-reset: earliest
            value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            properties:
                specific.avro.reader: true
        producer:
            value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
        ssl:
            protocol:
        properties:
            schema.registry.url: http://localhost:28081


kafka:
    topic: test
